-- 다중행 함수

-- SAL값들을 모두 합치기, (집계함수 SUM), 개별함수와 함께 사용할 수 없다.
SELECT  SUM(SAL) FROM EMP; 
-- 급여 합계 구하기
SELECT  SUM(DISTINCT SAL),SUM(ALL SAL),SUM(SAL) FROM EMP;

SELECT  * FROM EMP;
-- NULL은 COUNT에 포함되지 않는다.
SELECT COUNT(COMM) FROM EMP;
-- EMP 테이블의 데이터 개수 출력하기
SELECT COUNT(*) FROM EMP; 
-- 부서번호 30번의 데이터 개수
SELECT  COUNT(*) FROM EMP WHERE DEPTNO =30; 
-- DISTINCT 중복없이 처리, ALL 모두 처리
SELECT  COUNT(DISTINCT SAL), COUNT(ALL SAL), COUNT(SAL) FROM EMP; 
-- 추가 수당 열 개수
SELECT COUNT(COMM) FROM EMP WHERE COMM IS NOT NULL;
-- 부서 번호가 10번인 사원들의 최대/최소 급여 출력
SELECT  MAX(SAL) FROM EMP WHERE DEPTNO = 10;
SELECT MIN(SAL) FROM EMP WHERE DEPTNO = 10;
-- 부서 번호가 20번인 사원들중 제일 최근/오래된 입사일 출력
SELECT  MAX(HIREDATE) FROM EMP WHERE DEPTNO =20;
SELECT  MIN(HIREDATE) FROM EMP WHERE DEPTNO =20;
-- 부서 번호가 30번인 사람들의 평균 급여
SELECT AVG(SAL) FROM EMP WHERE DEPTNO =30;

-- GROUP BY절을 사용하여 부서별 평균 급여출력, GROUP BY -> 행의 갯수 결정, '그룹지어서 출력하겠다'
-- GROUP BY절을 이용하여 출력할 그룹 + 출력하고자 하는 내용, DEPTNO의 갯수에 따라서 행의 갯수 결정
-- GROUP BY절에 없는 열을 SELECT 절에 포함할 경우 오류
SELECT  DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO, COUNT(*) FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO, COUNT(*) AS ECOUNT FROM EMP GROUP BY DEPTNO ORDER BY ECOUNT DESC;
SELECT DEPTNO, JOB, AVG(SAL) AS ASAL FROM EMP GROUP BY DEPTNO,JOB ORDER BY ASAL DESC;

-- GROUP BY절을 통해 그룹화된 결과 값의 범위를 제한하는데 사용 -> HAVING , HAVING 절에는 별칭 사용 X
-- WHERE 는 GROUP 되기전에 필터링 (SELECT + FROM + WHERE + GROUP BY + HAVING + ORDER BY)
SELECT DEPTNO,JOB,AVG(SAL) FROM EMP GROUP BY DEPTNO,JOB HAVING AVG(SAL) >=2000 ORDER BY DEPTNO,JOB;
SELECT DEPTNO,JOB,AVG(SAL) FROM EMP WHERE SAL <= 3000 GROUP BY DEPTNO,JOB HAVING AVG(SAL) >= 2000 ORDER BY DEPTNO,JOB;