-- 시퀀스 생성
--CREATE SEQUENCE 시퀀스이름(테이블명_SEQ)

-- 제약조건 같이 복사되지 않음.
CREATE TABLE DEPT_SEQUENCE AS SELECT * FROM DEPT WHERE 1<>1;
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 10 START WITH 10 MAXVALUE 90 MINVALUE 0 NOCYCLE CACHE 2;

SELECT * FROM USER_SEQUENCES;

INSERT INTO DEPT_SEQUENCE(DEPTNO,DNAME,LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');
-- MAXVALUE 넘어서서 에러 메세지

SELECT  * FROM DEPT_SEQUENCE ORDER BY  DEPTNO;
-- 마지막으로 생성된 시퀀스 확인, *DUAL 행과열이 1개인 더미 테이블 (단순확인용)
SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;

 -- 시퀀스 수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 3 MAXVALUE 99 CYCLE;

SELECT * FROM USER_SEQUENCES;
-- 시퀀스 삭제
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

